// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── Miner → Server ───────────────────────────────────────────────────────
type MinerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MinerMessage_Register
	//	*MinerMessage_Ping
	//	*MinerMessage_Result
	Payload       isMinerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinerMessage) Reset() {
	*x = MinerMessage{}
	mi := &file_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerMessage) ProtoMessage() {}

func (x *MinerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerMessage.ProtoReflect.Descriptor instead.
func (*MinerMessage) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *MinerMessage) GetPayload() isMinerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MinerMessage) GetRegister() *MinerRegister {
	if x != nil {
		if x, ok := x.Payload.(*MinerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *MinerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*MinerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *MinerMessage) GetResult() *ProbeResult {
	if x != nil {
		if x, ok := x.Payload.(*MinerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isMinerMessage_Payload interface {
	isMinerMessage_Payload()
}

type MinerMessage_Register struct {
	Register *MinerRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type MinerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type MinerMessage_Result struct {
	Result *ProbeResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*MinerMessage_Register) isMinerMessage_Payload() {}

func (*MinerMessage_Ping) isMinerMessage_Payload() {}

func (*MinerMessage_Result) isMinerMessage_Payload() {}

type MinerRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // ed25519 public key hex
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`             // semver string, e.g. "0.1.0"
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`               // ISO 3166-1 alpha-2, e.g. "US"
	TimestampMs   uint64                 `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinerRegister) Reset() {
	*x = MinerRegister{}
	mi := &file_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerRegister) ProtoMessage() {}

func (x *MinerRegister) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerRegister.ProtoReflect.Descriptor instead.
func (*MinerRegister) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *MinerRegister) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MinerRegister) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MinerRegister) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *MinerRegister) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Ping) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// ─── Server → Miner ───────────────────────────────────────────────────────
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Pong
	//	*ServerMessage_JobBatch
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMessage) GetJobBatch() *JobBatch {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_JobBatch); ok {
			return x.JobBatch
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,1,opt,name=pong,proto3,oneof"`
}

type ServerMessage_JobBatch struct {
	JobBatch *JobBatch `protobuf:"bytes,2,opt,name=job_batch,json=jobBatch,proto3,oneof"`
}

func (*ServerMessage_Pong) isServerMessage_Payload() {}

func (*ServerMessage_JobBatch) isServerMessage_Payload() {}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	ServerTimeMs  uint64                 `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Pong) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type JobBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Jobs          []*Job                 `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobBatch) Reset() {
	*x = JobBatch{}
	mi := &file_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobBatch) ProtoMessage() {}

func (x *JobBatch) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobBatch.ProtoReflect.Descriptor instead.
func (*JobBatch) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *JobBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *JobBatch) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`              // UUID
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`  // fully qualified, e.g. "https://example.com/health"
	TimeoutMs     uint32                 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // per-probe wall-clock ceiling
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *Job) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// ─── Probe Result (Miner → Server) ────────────────────────────────────────
type ProbeResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JobId      string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	BatchId    string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	NodeId     string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TargetUrl  string                 `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Success    bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode uint32                 `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 0 when connection never established
	// Phase latencies in microseconds for sub-millisecond precision
	DnsUs         uint64 `protobuf:"varint,7,opt,name=dns_us,json=dnsUs,proto3" json:"dns_us,omitempty"`
	TcpUs         uint64 `protobuf:"varint,8,opt,name=tcp_us,json=tcpUs,proto3" json:"tcp_us,omitempty"`
	TlsUs         uint64 `protobuf:"varint,9,opt,name=tls_us,json=tlsUs,proto3" json:"tls_us,omitempty"` // 0 for plain HTTP
	TtfbUs        uint64 `protobuf:"varint,10,opt,name=ttfb_us,json=ttfbUs,proto3" json:"ttfb_us,omitempty"`
	TotalUs       uint64 `protobuf:"varint,11,opt,name=total_us,json=totalUs,proto3" json:"total_us,omitempty"`
	ErrorKind     string `protobuf:"bytes,12,opt,name=error_kind,json=errorKind,proto3" json:"error_kind,omitempty"` // empty on success; enum-like string from Rust
	ErrorMsg      string `protobuf:"bytes,13,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	TimestampMs   uint64 `protobuf:"varint,14,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProbeResult) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *ProbeResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ProbeResult) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *ProbeResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProbeResult) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProbeResult) GetDnsUs() uint64 {
	if x != nil {
		return x.DnsUs
	}
	return 0
}

func (x *ProbeResult) GetTcpUs() uint64 {
	if x != nil {
		return x.TcpUs
	}
	return 0
}

func (x *ProbeResult) GetTlsUs() uint64 {
	if x != nil {
		return x.TlsUs
	}
	return 0
}

func (x *ProbeResult) GetTtfbUs() uint64 {
	if x != nil {
		return x.TtfbUs
	}
	return 0
}

func (x *ProbeResult) GetTotalUs() uint64 {
	if x != nil {
		return x.TotalUs
	}
	return 0
}

func (x *ProbeResult) GetErrorKind() string {
	if x != nil {
		return x.ErrorKind
	}
	return ""
}

func (x *ProbeResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ProbeResult) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_monitor_proto protoreflect.FileDescriptor

const file_monitor_proto_rawDesc = "" +
	"\n" +
	"\rmonitor.proto\x12\amonitor\"\xa4\x01\n" +
	"\fMinerMessage\x124\n" +
	"\bregister\x18\x01 \x01(\v2\x16.monitor.MinerRegisterH\x00R\bregister\x12#\n" +
	"\x04ping\x18\x02 \x01(\v2\r.monitor.PingH\x00R\x04ping\x12.\n" +
	"\x06result\x18\x03 \x01(\v2\x14.monitor.ProbeResultH\x00R\x06resultB\t\n" +
	"\apayload\"}\n" +
	"\rMinerRegister\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x04R\vtimestampMs\"B\n" +
	"\x04Ping\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x04R\vtimestampMs\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"q\n" +
	"\rServerMessage\x12#\n" +
	"\x04pong\x18\x01 \x01(\v2\r.monitor.PongH\x00R\x04pong\x120\n" +
	"\tjob_batch\x18\x02 \x01(\v2\x11.monitor.JobBatchH\x00R\bjobBatchB\t\n" +
	"\apayload\"O\n" +
	"\x04Pong\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x04R\vtimestampMs\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x04R\fserverTimeMs\"G\n" +
	"\bJobBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12 \n" +
	"\x04jobs\x18\x02 \x03(\v2\f.monitor.JobR\x04jobs\"Z\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\"\x8a\x03\n" +
	"\vProbeResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x04 \x01(\tR\ttargetUrl\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\rR\n" +
	"statusCode\x12\x15\n" +
	"\x06dns_us\x18\a \x01(\x04R\x05dnsUs\x12\x15\n" +
	"\x06tcp_us\x18\b \x01(\x04R\x05tcpUs\x12\x15\n" +
	"\x06tls_us\x18\t \x01(\x04R\x05tlsUs\x12\x17\n" +
	"\attfb_us\x18\n" +
	" \x01(\x04R\x06ttfbUs\x12\x19\n" +
	"\btotal_us\x18\v \x01(\x04R\atotalUs\x12\x1d\n" +
	"\n" +
	"error_kind\x18\f \x01(\tR\terrorKind\x12\x1b\n" +
	"\terror_msg\x18\r \x01(\tR\berrorMsg\x12!\n" +
	"\ftimestamp_ms\x18\x0e \x01(\x04R\vtimestampMs2P\n" +
	"\x0eMonitorService\x12>\n" +
	"\tJobStream\x12\x15.monitor.MinerMessage\x1a\x16.monitor.ServerMessage(\x010\x01B\fZ\n" +
	"grpc/pb;pbb\x06proto3"

var (
	file_monitor_proto_rawDescOnce sync.Once
	file_monitor_proto_rawDescData []byte
)

func file_monitor_proto_rawDescGZIP() []byte {
	file_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_proto_rawDesc), len(file_monitor_proto_rawDesc)))
	})
	return file_monitor_proto_rawDescData
}

var file_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_monitor_proto_goTypes = []any{
	(*MinerMessage)(nil),  // 0: monitor.MinerMessage
	(*MinerRegister)(nil), // 1: monitor.MinerRegister
	(*Ping)(nil),          // 2: monitor.Ping
	(*ServerMessage)(nil), // 3: monitor.ServerMessage
	(*Pong)(nil),          // 4: monitor.Pong
	(*JobBatch)(nil),      // 5: monitor.JobBatch
	(*Job)(nil),           // 6: monitor.Job
	(*ProbeResult)(nil),   // 7: monitor.ProbeResult
}
var file_monitor_proto_depIdxs = []int32{
	1, // 0: monitor.MinerMessage.register:type_name -> monitor.MinerRegister
	2, // 1: monitor.MinerMessage.ping:type_name -> monitor.Ping
	7, // 2: monitor.MinerMessage.result:type_name -> monitor.ProbeResult
	4, // 3: monitor.ServerMessage.pong:type_name -> monitor.Pong
	5, // 4: monitor.ServerMessage.job_batch:type_name -> monitor.JobBatch
	6, // 5: monitor.JobBatch.jobs:type_name -> monitor.Job
	0, // 6: monitor.MonitorService.JobStream:input_type -> monitor.MinerMessage
	3, // 7: monitor.MonitorService.JobStream:output_type -> monitor.ServerMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_monitor_proto_init() }
func file_monitor_proto_init() {
	if File_monitor_proto != nil {
		return
	}
	file_monitor_proto_msgTypes[0].OneofWrappers = []any{
		(*MinerMessage_Register)(nil),
		(*MinerMessage_Ping)(nil),
		(*MinerMessage_Result)(nil),
	}
	file_monitor_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_Pong)(nil),
		(*ServerMessage_JobBatch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_proto_rawDesc), len(file_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_proto_depIdxs,
		MessageInfos:      file_monitor_proto_msgTypes,
	}.Build()
	File_monitor_proto = out.File
	file_monitor_proto_goTypes = nil
	file_monitor_proto_depIdxs = nil
}
