package workers

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"log"
	"time"

	"github.com/everestp/depin-backend/config/env"
	"github.com/everestp/depin-backend/db/repositories"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/gagliardetto/solana-go"
	"github.com/gagliardetto/solana-go/rpc"
)

const decimals = 1_000_000_000

// ─────────────────────────────────────────────
// WORKER START
// ─────────────────────────────────────────────

func StartSolanaSync(ctx context.Context, pool *pgxpool.Pool, cfg *env.Config) {

	store := repositories.NewStorage(pool)
	rpcClient := rpc.New(cfg.SolanaRPCURL)

	go func() {
		for {
			select {
			case <-ctx.Done():
				return
			default:
			}

			// 1. Fetch pending events (DB queue)
			events, err := store.SolanaSync.FetchPending(ctx, 10)
			if err != nil {
				log.Println("[solana-sync] fetch error:", err)
				time.Sleep(2 * time.Second)
				continue
			}

			for _, event := range events {

				// 2. Lock event for processing
				_ = store.SolanaSync.MarkProcessing(ctx, event.ID)

				// 3. Execute Solana transaction
				sig, err := executeRewardTx(
					ctx,
					rpcClient,
					cfg,
					event.RunnerPubkey,
					uint64(event.Amount*decimals),
				)

				if err != nil {
					log.Println("[solana-sync] tx failed:", err)

					_ = store.SolanaSync.MarkPendingAgain(ctx, event.ID)
					continue
				}

				// 4. Mark success
				_ = store.SolanaSync.MarkDone(ctx, event.ID, sig)

				log.Printf("[solana-sync] success: %s -> %s", event.RunnerPubkey, sig)
			}

			time.Sleep(2 * time.Second)
		}
	}()
}

// ─────────────────────────────────────────────
// SOLANA EXECUTION
// ─────────────────────────────────────────────

func executeRewardTx(
    ctx context.Context,
    client *rpc.Client,
    cfg *env.Config,
    ownerPubkey string,
    amountRaw uint64,
) (string, error) {

    backendSigner, err := cfg.GetBackendPrivateKey()
    if err != nil {
        return "", fmt.Errorf("invalid backend signer: %w", err)
    }

    programID := solana.MustPublicKeyFromBase58("DVicVozhh4y38dA6iCzfPp2c4xj5Q29mJq6HgF5Eufiz")
    nodePubkey := solana.MustPublicKeyFromBase58(ownerPubkey)

    // Derive the PDA using the same seeds as your Rust init_node function

emailHash := sha256.Sum256([]byte(ownerPubkey))

// Change the variable names: the second return value is the PublicKey
nodePDA, bump, err := solana.FindProgramAddress(
    [][]byte{
        []byte("node"),
        nodePubkey.Bytes(),
        emailHash[:],
    },
    programID,
)
if err != nil {
    return "", fmt.Errorf("failed to find PDA: %w", err)
}

// Now nodePDA is of type solana.PublicKey and can be used in NewAccountMeta
fmt.Printf("Derived PDA: %s (bump: %d)\n", nodePDA, bump)
    // Anchor Instruction Discriminator for "add_reward"
    // (Ensure this matches the one generated by your IDL)
    discriminator := [8]byte{108, 14, 219, 10, 116, 2, 237, 204}
    data := make([]byte, 16)
    copy(data[0:8], discriminator[:])
    binary.LittleEndian.PutUint64(data[8:16], amountRaw)

    // CORRECTED: Account meta order and flags to match AddReward struct
   instruction := solana.NewInstruction(
    programID,
    solana.AccountMetaSlice{
        // nodePDA: isSigner = false, isWritable = true
        solana.NewAccountMeta(nodePDA, false, true),
        
        // backendSigner: isSigner = true, isWritable = false
        solana.NewAccountMeta(backendSigner.PublicKey(), true, false),
    },
    data,
)

    recent, err := client.GetLatestBlockhash(ctx, rpc.CommitmentFinalized)
    if err != nil {
        return "", fmt.Errorf("blockhash error: %w", err)
    }

    tx, err := solana.NewTransaction(
        []solana.Instruction{instruction},
        recent.Value.Blockhash,
        solana.TransactionPayer(backendSigner.PublicKey()),
    )
    if err != nil {
        return "", fmt.Errorf("tx build error: %w", err)
    }

    _, err = tx.Sign(func(key solana.PublicKey) *solana.PrivateKey {
        if key.Equals(backendSigner.PublicKey()) {
            return &backendSigner
        }
        return nil
    })
    if err != nil {
        return "", fmt.Errorf("sign error: %w", err)
    }

    sig, err := client.SendTransaction(ctx, tx)
    if err != nil {
        return "", fmt.Errorf("send error: %w", err)
    }

    // ... (confirmation loop remains the same)
    return sig.String(), nil
}